config:
  # Logging Parameters
  logging_level: INFO
  # General Parameters (applies first)
  log_type: all
  event_distribution: wave
  # Linear Distribution Parameters (only applies if linear distribution)
  no_events: 2000
  write_time: 0.01
  # Wave Distribution Parameters (only applies if wave distribution)
  frequency: 3
  amplitude: 50
  sample_rate: 10
  duration: 60
  stretch: 0.5